# permissions for end users to view profilecatalogsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profilecatalogsource-viewer-role
rules:
- apiGroups:
  - profiles.weave.works
  resources:
  - profilecatalogsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - profiles.weave.works
  resources:
  - profilecatalogsources/status
  verbs:
  - get
